export const LOADING = 'LOADING';
export const LOADING_SAVE = 'LOADING_SAVE';
export const LOADING_FETCH = 'LOADING_FETCH';

export const LOAD_DRUGS_NAME_VALUESET = 'LOAD_DRUGS_NAME_VALUESET';
export const LOAD_DRUGS_NAME_VALUESET_SUCCESS ='LOAD_DRUGS_NAME_VALUESET_SUCCESS';
export const LOAD_DRUGS_NAME_VALUESET_FAIL = 'LOAD_DRUGS_NAME_VALUESET_FAIL';
export const LOADING_SEARCH_DRUG = 'LOADING_SEARCH_DRUG';

export const APPOINTMENT_INTENT_SET_DATA='APPOINTMENT_INTENT_SET_DATA';
export const APPOINTMENT_INTENT_SET_DATA_SUCCESS ='APPOINTMENT_INTENT_SET_DATA_SUCCESS';
export const APPOINTMENT_INTENT_SET_DATA_FAIL = 'APPOINTMENT_INTENT_SET_DATA_FAIL';

export const APPOINTMENT_PROTOCOL_SET_DATA='APPOINTMENT_PROTOCOL_SET_DATA';
export const APPOINTMENT_PROTOCOL_SET_DATA_SUCCESS ='APPOINTMENT_PROTOCOL_SET_DATA_SUCCESS';
export const APPOINTMENT_PROTOCOL_SET_DATA_FAIL = 'APPOINTMENT_PROTOCOL_SET_DATA_FAIL';


export const FIND_TREATMENT_PROTOCOL_LOAD='FIND_TREATMENT_PROTOCOL_LOAD';
export const FIND_TREATMENT_PROTOCOL_LOADING='FIND_TREATMENT_PROTOCOL_LOADING';
export const FIND_TREATMENT_PROTOCOL_SUCCESS ='FIND_TREATMENT_PROTOCOL_SUCCESS';
export const FIND_TREATMENT_PROTOCOL_FAIL = 'FIND_TREATMENT_PROTOCOL_FAIL';

export const TREATMENT_PATIENT_DETAILS_LOAD='TREATMENT_PATIENT_DETAILS_LOAD';
export const TREATMENT_PATIENT_DETAILS_LOADING='TREATMENT_PATIENT_DETAILS_LOADING';
export const TREATMENT_PATIENT_DETAILS_SUCCESS ='TREATMENT_PATIENT_DETAILS_SUCCESS';
export const TREATMENT_PATIENT_DETAILS_FAIL = 'TREATMENT_PATIENT_DETAILS_FAIL';
 
export const TREATMENT_LOAD_BMI_BSA = 'TREATMENT_LOAD_BMI_BSA';
export const TREATMENT_LOAD_BMI_BSA_SUCCESS = 'TREATMENT_LOAD_BMI_BSA_SUCCESS';
export const TREATMENT_LOAD_BMI_BSA_FAIL = 'TREATMENT_LOAD_BMI_BSA_FAIL';


export const TREATMENT_LOAD_DOSE_VALUESET = 'TREATMENT_LOAD_DOSE_VALUESET';
export const TREATMENT_LOAD_DOSE_VALUESET_SUCCESS = 'TREATMENT_LOAD_DOSE_VALUESET_SUCCESS';
export const TREATMENT_LOAD_DOSE_VALUESET_FAIL = 'TREATMENT_LOAD_DOSE_VALUESET_FAIL';


export const TREATMENT_LOAD_TIMING_VALUESET = 'TREATMENT_LOAD_TIMING_VALUESET';
export const TREATMENT_LOAD_TIMING_VALUESET_SUCCESS = 'TREATMENT_LOAD_TIMING_VALUESET_SUCCESS';
export const TREATMENT_LOAD_TIMING_VALUESET_FAIL = 'TREATMENT_LOAD_TIMING_VALUESET_FAIL';

export const TREATMENT_LOAD_DRUG_FORM_VALUESET = 'TREATMENT_LOAD_DRUG_FORM_VALUESET';
export const TREATMENT_LOAD_DRUG_FORM_VALUESET_SUCCESS ='TREATMENT_LOAD_DRUG_FORM_VALUESET_SUCCESS';
export const TREATMENT_LOAD_DRUG_FORM_VALUESET_FAIL = 'TREATMENT_LOAD_DRUG_FORM_VALUESET_FAIL';


export const TREATMENT_UNIT_SET_DATA = 'TREATMENT_UNIT_SET_DATA';
export const TREATMENT_UNIT_SET_DATA_SUCCESS ='TREATMENT_UNIT_SET_DATA_SUCCESS';
export const TREATMENT_UNIT_SET_DATA_FAIL = 'TREATMENT_UNIT_SET_DATA_FAIL';

export const TREATMENT_PROTOCOL_UNIT_SET_DATA = 'TREATMENT_PROTOCOL_UNIT_SET_DATA';
export const TREATMENT_PROTOCOL_UNIT_SET_DATA_SUCCESS ='TREATMENT_PROTOCOL_UNIT_SET_DATA_SUCCESS';
export const TREATMENT_PROTOCOL_UNIT_SET_DATA_FAIL = 'TREATMENT_PROTOCOL_UNIT_SET_DATA_FAIL';



export const TREATMENT_SAVE_PROTOCOL = 'TREATMENT_SAVE_PROTOCOL';
export const TREATMENT_SAVE_PROTOCOL_LOADING = 'TREATMENT_SAVE_PROTOCOL_LOADING';
export const TREATMENT_SAVE_PROTOCOL__SUCCESS  = 'TREATMENT_SAVE_PROTOCOL__SUCCESS ';
export const TREATMENT_SAVE_PROTOCOL_FAIL = 'TREATMENT_SAVE_PROTOCOL_FAIL';

export const TREATMENT_DO_PDF_INVOICE_SAVE = "TREATMENT_DO_PDF_INVOICE_SAVE";
export const TREATMENT_DO_PDF_INVOICE_SAVE_SUCCESS = "TREATMENT_DO_PDF_INVOICE_SAVE_SUCCESS";
export const TREATMENT_DO_PDF_INVOICE_SAVE_FAIL = "TREATMENT_DO_PDF_INVOICE_SAVE_FAIL";

export const TREATMENT_DO_SHARE_INVOICE = "TREATMENT_DO_SHARE_INVOICE";
export const TREATMENT_DO_SHARE_INVOICE_SUCCESS = "TREATMENT_DO_SHARE_INVOICE_SUCCESS";
export const TREATMENT_DO_SHARE_INVOICE_FAIL = "TREATMENT_DO_SHARE_INVOICE_FAIL";

export const TREATMENT_LOADING_PDF_SAVE = 'TREATMENT_LOADING_PDF_SAVE';
export const TREATMENT_LOADING_SHARE_INVOICE = 'TREATMENT_LOADING_SHARE_INVOICE';


export const TREATMENT_GET_PROTOCOL_FAIL = 'TREATMENT_GET_PROTOCOL_FAIL';
export const TREATMENT_GET_PROTOCOL_SUCCESS = 'TREATMENT_GET_PROTOCOL_SUCCESS';
export const TREATMENT_GET_PROTOCOL = 'TREATMENT_GET_PROTOCOL';
export const TREATMENT_GET_PROTOCOL_LOAD = 'TREATMENT_GET_PROTOCOL_LOAD';
export const TREATMENT_CLEAR_DATA = 'TREATMENT_CLEAR_DATA';

export const TREATMENT_FETCH_PRACTITIONER_DATABASE_SUCCESS = 'TREATMENT_FETCH_PRACTITIONER_DATABASE_SUCCESS';
export const TREATMENT_FETCH_PRACTITIONER_DATABASE_FAIL = 'TREATMENT_FETCH_PRACTITIONER_DATABASE_FAIL';
export const TREATMENT_FETCH_PRACTITIONER_DATABASE = 'TREATMENT_FETCH_PRACTITIONER_DATABASE';









