steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/nuqare-prod/github.com/dataquent/nuqare-web-app:$SHORT_SHA',  '-f', 'Dockerfile.prod' , '.' ]
  timeout: 900s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nuqare-prod/github.com/dataquent/nuqare-web-app:$SHORT_SHA']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubeconfig-prod.yaml
  - --image=gcr.io/nuqare-prod/github.com/dataquent/nuqare-web-app:$SHORT_SHA
  - --location=asia-south1-b
  - --cluster=nuqare-prod
  - --namespace=prod
timeout: 1200s
options:
  machineType: 'N1_HIGHCPU_8'