steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/oncoquent-dev-297911/github.com/dataquent/nuqare-web-app-base:0.1-baseline', '-f' , 'Dockerfile.npm' , '.' ]
  timeout: 900s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/oncoquent-dev-297911/github.com/dataquent/nuqare-web-app-base:0.1-baseline']
timeout: 1200s
options:
  machineType: 'N1_HIGHCPU_8'