---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nuqare-web-app"
  labels:
    run: "nuqare-web-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: "nuqare-web-app"
  template:
    metadata:
      labels:
        run: "nuqare-web-app"
    spec:
      containers:
      - name: "nuqare-web-app"
        image: "gcr.io/oncoquent-dev-297911/github.com/dataquent/nuqare-web-app"
---
apiVersion: v1
kind: Service
metadata:
  name: nuqare-web-app
  labels:
    run: nuqare-web-app
spec:
  type: NodePort  
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    run: nuqare-web-app