export const GET_PATIENT_EVERYTHING = `

query
PatientDataQuery($id:String!){
data:everything(patientEverythingCriteria:{
patientResourceId :$id,
nextResultUrl: null,
cancerResourceTypes:[
CANCER_PATIENT,
PRIMARY_CANCER_CONDITION,
SECONDARY_CANCER_CONDITION,
COMORBID_CONDITION,
PRESENT_ILLNESS,
CANCER_RELATED_SURGICAL_PROCEDURE,
CANCER_RELATED_SURGICAL_PROCEDURE_REQUEST,
CANCER_RELATED_SERVICE_REQUEST,
CANCER_RELATED_RADIATION_PROCEDURE,
CANCER_PATIENT_REPORTED_SYMPTOM,
CANCER_RELATED_ENCOUNTER_SURGICAL,
CANCER_RELATED_ENCOUNTER_OPD,
CARE_PLAN,
NUTRITION_ORDER,
CANCER_PATIENT_APPOINTMENT,
GENETIC_SPECIMEN,
CANCER_GENOMICS_REPORT,
CANCER_DIAGNOSTIC_REPORT,
CANCER_RELATED_MEDICATION_STATEMENT,
CANCER_RELATED_MEDICATION_REQUEST,
CANCER_RISK_ASSESSMENT,
ECOG_PERFORMANCE_STATUS,
KARNOFSKY_PERFORMANCE_STATUS,
CANCER_ALLERGY_INTOLERANCE,
CANCER_CLINICAL_IMPRESSION,
CANCER_IMMUNIZATION,
CANCER_DISEASE_STATUS,
PAST_HOSPITALIZATION_HISTORY,
TNM_CLINICAL_STAGE_GROUP,
TNM_CLINICAL_PRIMARY_TUMOR_CATEGORY,
TNM_PATHOLOGICAL_PRIMARY_TUMOR_CATEGORY,
TNM_PATHOLOGICAL_STAGE_GROUP,
TNM_POST_THERAPY_PRIMARY_TUMOR_CATEGORY,
TNM_POST_THERAPY_STAGE_GROUP,
MOOD_CAPTURE,
LIFE_STYLE_INDICATOR,
EXAMINATION_OBSERVATION,
CLINICAL_COMPLAINS_OBSERVATION,
RECIST_OBSERVATION,
ACTIVITY_OBSERVATION,
FOOD_OBSERVATION,
SLEEP_OBSERVATION,
CANCER_GENETIC_VARIANT,
GENOMIC_REGION_STUDIED,
VITAL_SIGNS,
TUMOR_MARKER,
FAMILY_MEMBER_HISTORY,
CANCER_DOCUMENT_REFERENCE,
CANCER_COMMUNICATION,
EXAMINATION_OBSERVATION
]
})
{
 nextResultUrl,
 recordCount,
 patient
 {
   resourceId,
   active,
   gender,
   display,
   first,
   middle,
   birthDate,
   occupation,
   bloodGroup,
   height
   {
       value
   }
   last,
   email,
   patientIdentifier,
   communicationLanguage,
   deceasedDateTime,
   isDeceased,
   age,
   phone,
   image,
   maritalStatus
   {
       code,
       display,
       text
   },
   addressDetail{
        line,
        city,
        state,
        district,
        addressType,
        postalCode
   }
   homePhone,
   workPhone,
   referredByName,
   referredByContactNumber,
   policyNumber,
   providerName,
   isDiebetes,
   isCOPD,
   isCVD,
   isCHF
 },
 geriatricQuestionnaireResponse
 {
   resourceId,
   status,
   date,
   questionnaire,
   reportedAnswer
   {
       question,
       score,
       response
   }
 },
 cancerGeriatricAssessment
 {
     resourceId,
     value,
     effectiveDateTime
 },
 cancerDocumentReferences
 {
     resourceId,
           status,
           docStatus,
           date,
           description,
            type
           {
               codeableSystem,
               code,
               text,
               display
           },
            category
           {
               codeableSystem,
               code,
               text,
               display
           },
           author
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           authenticator
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
            cancerPatientResourceReference
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
             custodian
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           relatesTo
           {
               code,
               target
              {
               resourceId,
               resourceType,
               resourceReference,
               display
               }
           },
           content
           {
               attachment
               {
                   contentType,
                   url,
                   size,
                   title,
                   hash,
                   creation
               },
               format
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
           }
 },
 visitNote
 {
          resourceId,
           status,
           docStatus,
           date,
           description,
            type
           {
               codeableSystem,
               code,
               text,
               display
           },
            category
           {
               codeableSystem,
               code,
               text,
               display
           },
           author
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           authenticator
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
            cancerPatientResourceReference
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
             custodian
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           relatesTo
           {
               code,
               target
              {
               resourceId,
               resourceType,
               resourceReference,
               display
               }
           },
           content
           {
               attachment
               {
                   contentType,
                   url,
                   size,
                   title,
                   hash,
                   creation
               },
               format
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
           }
 },
 caseSummary
 {
     resourceId,
           status,
           docStatus,
           date,
           description,
            type
           {
               codeableSystem,
               code,
               text,
               display
           },
            category
           {
               codeableSystem,
               code,
               text,
               display
           },
           author
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           authenticator
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
            cancerPatientResourceReference
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
             custodian
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           relatesTo
           {
               code,
               target
              {
               resourceId,
               resourceType,
               resourceReference,
               display
               }
           },
           content
           {
               attachment
               {
                   contentType,
                   url,
                   size,
                   title,
                   hash,
                   creation
               },
               format
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
           }
 },
 treatmentSummary
 {
     resourceId,
           status,
           docStatus,
           date,
           description,
            type
           {
               codeableSystem,
               code,
               text,
               display
           },
            category
           {
               codeableSystem,
               code,
               text,
               display
           },
           author
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           authenticator
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
            cancerPatientResourceReference
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
             custodian
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           relatesTo
           {
               code,
               target
              {
               resourceId,
               resourceType,
               resourceReference,
               display
               }
           },
           content
           {
               attachment
               {
                   contentType,
                   url,
                   size,
                   title,
                   hash,
                   creation
               },
               format
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
           }
 },
 activityObservations
 {
     resourceId,
     status,
     code,
     effectiveDateTime,
      valueQuantity
               {
                   system,
                   code,
                   unit,
                   value
               },
                valueCodeableConcept
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
      cancerPatientResourceReference
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           component
           {
                code
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
               valueQuantity
               {
                   system,
                   code,
                   unit,
                   value
               },
                valueCodeableConcept
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
           }
 },
 foodObservations
 {
     resourceId,
     status,
     code,
     effectiveDateTime,
      valueQuantity
               {
                   system,
                   code,
                   unit,
                   value
               },
                valueCodeableConcept
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
      cancerPatientResourceReference
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           component
           {
                code
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
               valueQuantity
               {
                   system,
                   code,
                   unit,
                   value
               },
                valueCodeableConcept
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
           }
 },
 sleepObservations
 {
     resourceId,
     status,
     code,
     effectiveDateTime,
      valueQuantity
               {
                   system,
                   code,
                   unit,
                   value
               },
                valueCodeableConcept
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
      cancerPatientResourceReference
           {
              resourceId,
              resourceType,
              resourceReference,
              display
           },
           component
           {
                code
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
               valueQuantity
               {
                   system,
                   code,
                   unit,
                   value
               },
                valueCodeableConcept
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
           }
 },
 oBGYNObservation
 {
     effectiveDateTime,
               code
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
               valueQuantity
               {
                  unit,
                  value
               },
                valueCodeableConcept
               {
                   codeableSystem,
                   code,
                   text,
                   display
               },
               component
               {
                        code
                        {
                            codeableSystem,
                            code,
                            text,
                            display
                        },
                         valueQuantity
                        {
                            unit,
                            value
                        },
                        valueCodeableConcept
                        {
                            codeableSystem,
                            code,
                            text,
                            display
                        },
               }
 },
 primaryCancerCondition
 {
        resourceId,
         clinicalStatus
       {
           codeableSystem,
           code,
           text,
           display
       },
        verificationStatus
       {
           codeableSystem,
           code,
           text,
           display
       },
       bodySideWithLaterality
       {
            bodySite
         {
            codeableSystem,
            code,
            text,
            display
        },
            laterality
        {
            codeableSystem,
            code,
            text,
            display
        }
       },
        histologyMorphologyBehaviour
       {
           codeableSystem,
           code,
           text,
           display
       },
       onset,
       category,
       code
       {
           codeableSystem,
           code,
           text,
           display
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        asserter
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       stage
       {
            summary
           {
               codeableSystem,
               code,
               text,
               display
           },
            assessment
           {
               resourceId,
               resourceType,
               resourceReference,
               display
           }
       }
 },
 secondaryCancerConditions
 {
       resourceId,
         clinicalStatus
       {
           codeableSystem,
           code,
           text,
           display
       },
        verificationStatus
       {
           codeableSystem,
           code,
           text,
           display
       },
        bodySideWithLaterality
       {
            bodySite
         {
            codeableSystem,
            code,
            text,
            display
        },
            laterality
        {
            codeableSystem,
            code,
            text,
            display
        }
       },
       histologyMorphologyBehaviour
       {
           codeableSystem,
           code,
           text,
           display
       },
       onset,
       category,
       code
       {
           codeableSystem,
           code,
           text,
           display
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        asserter
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        relatedPrimaryCondition
        {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
 },
 comorbidConditions
 {
      resourceId,
         clinicalStatus
       {
           codeableSystem,
           code,
           text,
           display
       },
        verificationStatus
       {
           codeableSystem,
           code,
           text,
           display
       },
       onset,
       duration,
       category,
       code
       {
           codeableSystem,
           code,
           text,
           display
       },
       note,
        bodySideWithLaterality
       {
            bodySite
         {
            codeableSystem,
            code,
            text,
            display
        },
            laterality
        {
            codeableSystem,
            code,
            text,
            display
        }
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        asserter
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       stage
       {
           summary
           {
                 codeableSystem,
                   code,
                   text,
                   display
           },
           assessment
           {
               resourceId,
               resourceType,
               resourceReference,
               display
           }
       }
 }
 cancerServiceRequests
 {
   resourceId,
    encounter{
        resourceId,
        resourceType,
        resourceReference,
        display
    },
   status,
   intent,
   priority,
   fromDate,
   toDate,
    code
   {
       codeableSystem,
       code,
       text,
       display
   },
   category
   {
       codeableSystem,
       code,
       text,
       display
   },
   cancerLocationResourceReference
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
   requester
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
    bodySite
   {
      codeableSystem,
       code,
       text,
       display
   },
     reasonCode
   {
      codeableSystem,
       code,
       text,
       display
   }
 },
 cancerSurgicalServiceRequests
 {
   resourceId,
   status,
   intent,
   priority,
   fromDate,
   toDate,
    code
   {
       codeableSystem,
       code,
       text,
       display
   },
   category
   {
       codeableSystem,
       code,
       text,
       display
   },
   cancerLocationResourceReference
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
   requester
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
    bodySite
   {
      codeableSystem,
       code,
       text,
       display
   },
     reasonCode
   {
      codeableSystem,
       code,
       text,
       display
   }
 },
 cancerRadiationServiceRequests
 {
    resourceId,
   status,
   intent,
   priority,
   fromDate,
   toDate,
    code
   {
       codeableSystem,
       code,
       text,
       display
   },
   category
   {
       codeableSystem,
       code,
       text,
       display
   },
   cancerLocationResourceReference
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
   requester
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
    bodySite
   {
      codeableSystem,
       code,
       text,
       display
   },
     reasonCode
   {
      codeableSystem,
       code,
       text,
       display
   }
 },
 cancerSurgicalProcedures
 {
     resourceId,
     startDate,
     status,
     note,
     code
     {
       codeableSystem,
       code,
       text,
       display
     },
     bodySideWithLaterality
     {
        bodySite
        {
        codeableSystem,
        code,
        text,
        display
        },
        laterality
        {
        codeableSystem,
        code,
        text,
        display
        }
     },
       followup
     {
       codeableSystem,
       code,
       text,
       display
     },
       complication
     {
       codeableSystem,
       code,
       text,
       display
     },
       outcome
     {
       codeableSystem,
       code,
       text,
       display
     },
       reasonCode
     {
       codeableSystem,
       code,
       text,
       display
     },
      notPerformedReason
     {
       codeableSystem,
       code,
       text,
       display
     },
     treatmentIntent
     {
       codeableSystem,
       code,
       text,
       display
     },
     cancerPatientResourceReference
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
   reasonReference
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
   asserter
   {
      resourceId,
      resourceType,
      resourceReference,
      display
   },
     category
 },
 cancerRadiationProcedures
 {
     resourceId,
     status,
     startDate,
     endDate,
     note,
      code
       {
           codeableSystem,
           code,
           text,
           display
       },
       bodySideWithLaterality
       {
            laterality
          {
            codeableSystem,
            code,
            text,
            display
        },
            bodySite
        {
            codeableSystem,
            code,
            text,
            display
        }
       },
         treatmentIntent
       {
           codeableSystem,
           code,
           text,
           display
       },
         followup
       {
           codeableSystem,
           code,
           text,
           display
       },
         complication
       {
           codeableSystem,
           code,
           text,
           display
       },
         outcome
       {
           codeableSystem,
           code,
           text,
           display
       },
         reasonCode
       {
           codeableSystem,
           code,
           text,
           display
       },
         notPerformedReason
       {
           codeableSystem,
           code,
           text,
           display
       },
       reasonReference
       {
       resourceId,
       resourceType,
       resourceReference,
       display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        asserter
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       performers
       {
           resourceId,
             performerFunction
           {
               codeableSystem,
               code,
               text,
               display
           },
            actor
           {
               resourceId,
               resourceType,
               resourceReference,
               display
           },
           onBehalfOf
           {
               resourceId,
               resourceType,
               resourceReference,
               display
           },
       }
 },
 cancerPatientReportedSymptoms
  {
    resourceId,
    status,
    date,
    subject
    {
        display,
        resourceId,
        resourceReference
    },
    author
    {
       display,
        resourceId,
        resourceReference
    },
    reportedSymptom
    {
        code,
        response
    }
  },
   eCOGPerformanceStatus
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
       interpretation
       {
           codeableSystem,
           code,
           text,
           display
       },
       method
       {
           codeableSystem,
           code,
           text,
           display
       },
       performer
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       status,
       effectiveDateTime,
       valueInteger
   },
   karnofskyPerformanceStatus
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
       interpretation
       {
           codeableSystem,
           code,
           text,
           display
       },
       method
       {
           codeableSystem,
           code,
           text,
           display
       },
       performer
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       status,
       effectiveDateTime,
       valueInteger
   },
   tumorMarkers
   {
       resourceId,
       code
       {
           codeableSystem,
           code,
           text,
           display
       },
        category
       {
           codeableSystem,
           code,
           text,
           display
       },
       valueCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       },
       valueQuantity
       {
           system,
           unit,
           value,
           code
       },
        interpretation
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       status,
       effectiveDateTime,
       note
   },
   vitalSigns
   {
       resourceId,
       code
       {
           codeableSystem,
           code,
           text,
           display
       },
       performer
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }, 
       hasMembers
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        evidenceType
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       value
       {
           value,
           system,
           unit,
           code
       },
       valueCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       }
       status,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
       effectiveDateTime,
       dataAbsentReason
        {
           codeableSystem,
           code,
           text,
           display
       }
   },  
   cancerMedicationStatements
   {
       resourceId,
       status,
       start,
       end,
       dateAsserted,
       statusReason
       {
               codeableSystem,
               code,
               text,
               display
       },
       reasonCode
       {
               codeableSystem,
               code,
               text,
               display
       },
       reasonReference
       {
            resourceId,
           resourceType,
           resourceReference,
           display
       },
        medicationCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       }
        informationSource
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        dosageInstruction
       {
           method
         {
               codeableSystem,
               code,
               text,
               display
           },
           route
          {
               codeableSystem,
               code,
               text,
               display
           },
           doseQuantity
           {
               system,
               unit,
               value,
               code
           }
            numerator
           {
               system,
               unit,
               value,
               code
           },
            denominator
           {
               system,
               unit,
               value,
               code
           },
           start,
           end,
           patientInstruction,
           text
       }

   },
   supportiveCareMedicationStatements
   {
          resourceId,
       status,
       start,
       end,
       dateAsserted,
       statusReason
       {
               codeableSystem,
               code,
               text,
               display
       },
       reasonCode
       {
               codeableSystem,
               code,
               text,
               display
       },
       reasonReference
       {
            resourceId,
           resourceType,
           resourceReference,
           display
       },
        medicationCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       }
        informationSource
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        dosageInstruction
       {
           method
         {
               codeableSystem,
               code,
               text,
               display
           },
           route
          {
               codeableSystem,
               code,
               text,
               display
           },
           doseQuantity
           {
               system,
               unit,
               value,
               code
           }
            numerator
           {
               system,
               unit,
               value,
               code
           },
            denominator
           {
               system,
               unit,
               value,
               code
           },
           start,
           end,
           patientInstruction,
           text
       }

   },
   pRRTMedicationStatements
   {
          resourceId,
       status,
       start,
       end,
       dateAsserted,
       statusReason
       {
               codeableSystem,
               code,
               text,
               display
       },
       reasonCode
       {
               codeableSystem,
               code,
               text,
               display
       },
        medicationCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       }
        informationSource
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
   },
   chemoMedicationStatements
   {
          resourceId,
       status,
       start,
       end,
       dateAsserted,
       statusReason
       {
               codeableSystem,
               code,
               text,
               display
       },
       reasonCode
       {
               codeableSystem,
               code,
               text,
               display
       },
        medicationCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       }
        informationSource
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        dosageInstruction
       {
           method
         {
               codeableSystem,
               code,
               text,
               display
           },
           route
          {
               codeableSystem,
               code,
               text,
               display
           },
           doseQuantity
           {
               system,
               unit,
               value,
               code
           }
            numerator
           {
               system,
               unit,
               value,
               code
           },
            denominator
           {
               system,
               unit,
               value,
               code
           },
           start,
           end,
           patientInstruction,
           text
       }

   },
   immunoMedicationStatements
   {
          resourceId,
       status,
       start,
       end,
       dateAsserted,
       statusReason
       {
               codeableSystem,
               code,
               text,
               display
       },
       reasonCode
       {
               codeableSystem,
               code,
               text,
               display
       },
        medicationCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       }
        informationSource
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
   },
   conservativeMedicationStatements
   {
         resourceId,
       status,
       start,
       end,
       dateAsserted,
       statusReason
       {
               codeableSystem,
               code,
               text,
               display
       },
       reasonCode
       {
               codeableSystem,
               code,
               text,
               display
       },
        medicationCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       }
        informationSource
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
   },
   cancerPatientRiskAssessment
   {
       resourceId,
       status,
       occuranceDate,
       basis,
       cancerPatientResourceReference
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       },
       cancerRiskAssessmentPrediction
       {
           qualitativeRisk,
           outcome
           {
               cancerType,
               bodysite,
               factors
           },
           qualitativeRiskDisplay
       }
   },
   cancerImmunizations
   {
     resourceId,
     status,
     occurrence,
     primarySource,
     recorded,
     lotNumber,
     expirationDate,
     note,
     doseQuantity
     {
         system,
         code,
         unit,
         value
     },
     vaccineCode
     {
         codeableSystem,
               code,
               text,
               display
     },
     patient
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       },
        route
     {
         codeableSystem,
               code,
               text,
               display
     },
      site
     {
         codeableSystem,
               code,
               text,
               display
     },
      reportOrigin
     {
         codeableSystem,
               code,
               text,
               display
     },
     performer
     {
        function
        {
            codeableSystem,
               code,
               text,
               display
        },
        actor
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       }
     },
     protocolApplied
     {
        series,
        seriesDoses,
        doseNumber,
         authority
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       },
       targetDisease
       {
           codeableSystem,
               code,
               text,
               display
       }
     }
   },
   cancerAllergyIntolerances
   {
       resourceId,
       type,
       criticality,
       onset,
       recordedDate,
       lastOccurrence,
       note,
       category,
       clinicalStatus
           {
               codeableSystem,
               code,
               text,
               display
           },
           verificationStatus
           {
               codeableSystem,
               code,
               text,
               display
           },
            code
           {
               codeableSystem,
               code,
               text,
               display
           },
        asserter
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       },
         patient
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       },
         recorder
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       },
       reaction
       {
           description,
           severity,
           onsetReaction,
           noteReaction,
            substance
           {
               codeableSystem,
               code,
               text,
               display
           },
            exposureRoute
           {
               codeableSystem,
               code,
               text,
               display
           },
            manifestation
           {
               codeableSystem,
               code,
               text,
               display
           },
       }
   },
   cancerClinicalImpressions
   {
    resourceId
     status,
     date,
     description,
     protocol,
     cancerPatientResourceReference
     {
          resourceId,
            resourceType,
           resourceReference,
           display  
     },
     investigation
     {
         code
         {
             codeableSystem,
               code,
               text,
               display
         },
         item
         {
              resourceId,
            resourceType,
           resourceReference,
           display  
         }
     }
   },
   cancerEncounterOPDs
   {
       resourceId,
       statusHistory
       {
           status,
           startDate,
           endDate
       },
       status,
       startDate,
       endDate,
        class
        {   
            codeableSystem,
               code,
               text,
               display
       }, 
        reasonCode
        {
            codeableSystem,
               code,
               text,
               display
       }, 
       reAdmission
           {
               codeableSystem,
               code,
               text,
               display
       },
        admitSource
           {
               codeableSystem,
               code,
               text,
               display
       },
       cancerPatientResourceReference
       {
             resourceId,
            resourceType,
           resourceReference,
           display 
       },
        location
       {
           location
           {
                   resourceId,
               resourceType,
               resourceReference,
               display 
           },
               status,
           startDate,
           endDate,
       },
       appointment
       {
             resourceId,
            resourceType,
           resourceReference,
           display 
       },
       reasonReference
       {
             resourceId,
            resourceType,
           resourceReference,
           display 
       },
       account
       {
            resourceId,
            resourceType,
           resourceReference,
           display 
       }          
   },
   cancerEncounterSurgicals
   {
        resourceId,
       statusHistory
       {
           status,
           startDate,
           endDate
       },
       status,
       startDate,
       endDate,
        class
        {   
            codeableSystem,
               code,
               text,
               display
       }, 
        reasonCode
        {
            codeableSystem,
               code,
               text,
               display
       }, 
       reAdmission
           {
               codeableSystem,
               code,
               text,
               display
       },
        admitSource
           {
               codeableSystem,
               code,
               text,
               display
       },
       cancerPatientResourceReference
       {
             resourceId,
            resourceType,
           resourceReference,
           display 
       },
        location
       {
               location
           {
                   resourceId,
               resourceType,
               resourceReference,
               display 
           },
               status,
           startDate,
           endDate,
       },
       appointment
       {
             resourceId,
            resourceType,
           resourceReference,
           display 
       },
       reasonReference
       {
             resourceId,
            resourceType,
           resourceReference,
           display 
       },
       account
       {
            resourceId,
            resourceType,
           resourceReference,
           display 
       }
   },
   cancerDiagnosticReports
   {
       resourceId,
       status,
       effectiveDateTime,
       issued,
       code
       {
          codeableSystem,
               code,
               text,
               display
       },
        category
        {
               codeableSystem,
               code,
               text,
               display
           },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       performer
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       conclusionCode
       {
           codeableSystem,
               code,
               text,
               display
       }
   },
   cancerDiseaseStatus
   {
      resourceId,
      category
           {
               codeableSystem,
               code,
               text,
               display
           },
        conditionStatusTrendValue
           {
               codeableSystem,
               code,
               text,
               display
           },
            evidenceType
           {
               codeableSystem,
               code,
               text,
               display
           },
        cancerPatientResourceReference
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       },
         performer
       {
            resourceId,
            resourceType,
           resourceReference,
           display   
       },
       status,
       code,
       effectiveDateTime
   },
    moodCaptures
   {
       resourceId,
       code{
           codeableSystem,
           code,
           text,
           display
       },
       valueInteger,
       status,
       note,
       effectiveDateTime,
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
   },
     tNMClinicalStageGroup
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       tNMClinicalCategoryResourceReferences
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
       code,
       status,
       effectiveDate
   },
    tNMClinicalPrimaryTumorCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
    tNMClinicalDistantMetastasesCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
    tNMClinicalRegionalNodesCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
     tNMPathologicalStageGroup
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
     tNMPathologicalRegionalNodesCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
     tNMPathologicalPrimaryTumorCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
     tNMPathologicalDistantMetastasesCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },

     tNMPostTherapyStageGroup
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       tNMPostTherapyCategoryResourceReferences
       {
          resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
     tNMPostTherapyRegionalNodesCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
     tNMPostTherapyPrimaryTumorCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
     tNMPostTherapyDistantMetastasesCategory
   {
       resourceId,
       category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       value
       {
           codeableSystem,
           code,
           text,
           display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        code,
       status,
       effectiveDate
   },
   cancerGeneticVariants
   {
       resourceId,
       effectiveDateTime,
       status,
       code,
         valueCodeableConcept
       {
           codeableSystem,
           code,
           text,
           display
       },
        category
       {
           codeableSystem,
           code,
           text,
           display
       },
       component
       {
             code
           {
               codeableSystem,
               code,
               text,
               display
           },
             valueCodeableConcept
           {
               codeableSystem,
               code,
               text,
               display
           },
           valueQuantity
           {
               system,
               unit,
               value,
               code
           }
       }
         cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         performer
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         specimen
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
   },
   genomicRegionStudies
   {
       resourceId,
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         performer
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        category
       {
           codeableSystem,
           code,
           text,
           display
       },
        method
       {
           codeableSystem,
           code,
           text,
           display
       },
       component
       {
             code
           {
               codeableSystem,
               code,
               text,
               display
           },
             valueCodeableConcept
           {
               codeableSystem,
               code,
               text,
               display
           },
           valueQuantity
           {
               system,
               unit,
               value,
               code
           }
       },
       code
       effectiveDateTime,
       status,
       issued
   },
   geneticSpecimens
   {
       resourceId,
        method
           {
               codeableSystem,
               code,
               text,
               display
           },
            bodySite
           {
               codeableSystem,
               code,
               text,
               display
           },
             type
           {
               codeableSystem,
               code,
               text,
               display
           },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       collector
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       status,
       receivedTime
   },
   cancerGenomicsReports
   {
       resourceId,
       status,
       effectiveDateTime,
       issued,
        category
        {
               codeableSystem,
               code,
               text,
               display
           },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       specimen
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       result
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       }
   },
   regimenProtocolRequests
   {
      resourceId,
      regimen,
      cycle,
      regimenTreatment,
      authoredOn
       status,
       intent,
        category
        {
               codeableSystem,
               code,
               text,
               display
           },
        treatmentIntent
        {
               codeableSystem,
               code,
               text,
               display
           },
        medicationCodeableConcept
        {
               codeableSystem,
               code,
               text,
               display
           },
       medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         requester
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       dosageInstruction
       {
           method
         {
               codeableSystem,
               code,
               text,
               display
           },
           route
          {
               codeableSystem,
               code,
               text,
               display
           },
           doseQuantity
           {
               system,
               unit,
               value,
               code
           }
            numerator
           {
               system,
               unit,
               value,
               code
           },
            denominator
           {
               system,
               unit,
               value,
               code
           },
           start,
           end,
           patientInstruction,
           text,
           period,
           periodMax,
           periodUnit,
           count,
           countMax,
           duration,
           durationMax,
           durationUnit,
           code{
                codeableSystem,
               code,
               text,
               display
           },
           when,
           dayOfWeek,
           timeOfDay,
       }
   },
   cancerMedicationRequests
   {
       resourceId,
       encounter{
            resourceId,
            resourceType,
            resourceReference,
            display
        },
       authoredOn
       status,
       intent,
        category
        {
               codeableSystem,
               code,
               text,
               display
           },
        treatmentIntent
        {
               codeableSystem,
               code,
               text,
               display
           },
        medicationCodeableConcept
        {
               codeableSystem,
               code,
               text,
               display
           },
       medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         requester
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       dosageInstruction
       {
           method
         {
               codeableSystem,
               code,
               text,
               display
           },
           route
          {
               codeableSystem,
               code,
               text,
               display
           },
           doseQuantity
           {
               system,
               unit,
               value,
               code
           }
            numerator
           {
               system,
               unit,
               value,
               code
           },
            denominator
           {
               system,
               unit,
               value,
               code
           },
           start,
           end,
           patientInstruction,
           text,
           period,
           periodMax,
           periodUnit,
           count,
           countMax,
           duration,
           durationMax,
           durationUnit,
           code{
                codeableSystem,
               code,
               text,
               display
           },
           when,
           dayOfWeek,
           timeOfDay,
       }

   },
   pRRTMedicationRequests
   {
       resourceId,
       authoredOn
       status,
       intent,
        category
        {
               codeableSystem,
               code,
               text,
               display
           },
        treatmentIntent
        {
               codeableSystem,
               code,
               text,
               display
           },
        medicationCodeableConcept
        {
               codeableSystem,
               code,
               text,
               display
           },
       medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         requester
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       dosageInstruction
       {
           method
         {
               codeableSystem,
               code,
               text,
               display
           },
           route
          {
               codeableSystem,
               code,
               text,
               display
           },
           doseQuantity
           {
               system,
               unit,
               value,
               code
           }
            numerator
           {
               system,
               unit,
               value,
               code
           },
            denominator
           {
               system,
               unit,
               value,
               code
           },
           start,
           end,
           patientInstruction,
           text
       }

   },
   immunoMedicationRequests
   {
       resourceId,
       authoredOn
       status,
       intent,
        category
        {
               codeableSystem,
               code,
               text,
               display
           },
        treatmentIntent
        {
               codeableSystem,
               code,
               text,
               display
           },
        medicationCodeableConcept
        {
               codeableSystem,
               code,
               text,
               display
           },
       medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         requester
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       dosageInstruction
       {
           method
         {
               codeableSystem,
               code,
               text,
               display
           },
           route
          {
               codeableSystem,
               code,
               text,
               display
           },
           doseQuantity
           {
               system,
               unit,
               value,
               code
           }
            numerator
           {
               system,
               unit,
               value,
               code
           },
            denominator
           {
               system,
               unit,
               value,
               code
           },
           start,
           end,
           patientInstruction,
           text
       }

   },
   chemoMedicationRequests
   {
       resourceId,
       authoredOn
       status,
       intent,
        category
        {
               codeableSystem,
               code,
               text,
               display
           },
        treatmentIntent
        {
               codeableSystem,
               code,
               text,
               display
           },
        medicationCodeableConcept
        {
               codeableSystem,
               code,
               text,
               display
           },
       medicationResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
         requester
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       dosageInstruction
       {
           method
         {
               codeableSystem,
               code,
               text,
               display
           },
           route
          {
               codeableSystem,
               code,
               text,
               display
           },
           doseQuantity
           {
               system,
               unit,
               value,
               code
           }
            numerator
           {
               system,
               unit,
               value,
               code
           },
            denominator
           {
               system,
               unit,
               value,
               code
           },
           start,
           end,
           patientInstruction,
           text
       }

   },
   nonCancerSpecificProcedures
   {
       id,
       category
       {
           text,
           coding
           {
               code,
               display
           }
       },
        statusReason
       {
           text,
           coding
           {
               code,
               display
           }
       },
        reasonCode
       {
           text,
           coding
           {
               code,
               display
           }
       },
        outcome
       {
           text,
           coding
           {
               code,
               display
           }
       },
        complication
       {
           text,
           coding
           {
               code,
               display
           }
       },
        followUp
       {
           text,
           coding
           {
               code,
               display
           }
       },
        bodySite
       {
           text,
           coding
           {
               code,
               display
           }
       },
        code
       {
           text,
           coding
           {
               code,
               display
           }
       },
       asserter
       {
           reference
       }
        subject
       {
           reference
       },
       status,
       performedPeriod
       {
           start,
           end
       },
       note
       {
           text
           {
               value
           }
       },
       performer
       {
           function
           {
               text,
               coding
               {
                   code,
                   display
               }
          },
           actor
            {
              reference
            },
           onBehalfOf
           {
              reference
           }
       }
   },
   nonCancerSpecificConditions
   {
       id,
       onset,
        code
       {
           text,
           coding
           {
               code,
               display
           }
       },
       asserter
       {
           reference
       }
        category
       {
           text,
           coding
           {
               code,
               display
           }
       },
       subject
       {
           reference,
           display
       },
        verificationStatus
       {
           text,
           coding
           {
               code,
               display
           }
       },
        clinicalStatus
       {
           text,
           coding
           {
               code,
               display
           }
       }
   },
   treatmentCarePlan
   {
      resourceId
   }
   carePlan
   {
       resourceId,
       description,
   },
   careNutritionOrder
   {
       resourceId,
       dateTime,
       oralInstruction
   },
   scheduledFollowup
   {
      resourceId,
      startDateTime
   },
    nonCancerSpecificObservations
   {
       id,
        category
        {
           text,
           coding
           {
               code,
               display
           }
       },
       code
        {
           text,
           coding
           {
               code,
               display
           }
       },
       interpretation
        {
           text,
           coding
           {
               code,
               display
           }
       },
       method
        {
           text,
           coding
           {
               code,
               display
           }
       },  
       status,
       effective, 
         value{
            system,
            unit,
            value,
            code
       },
       subject{
           reference,
           display
       },
        performer{
           reference,
           display
       } , 
       component
       {
            value{
               system,
               unit,
               value,
               code
            },
           code
           {
               text,
               coding
               {
                   code,
                   display
               }
           }
       }
   },
    nonCancerSpecificValueCodeableObservations
   {
       id,
        category
        {
           text,
           coding
           {
               code,
               display
           }
       },
       code
        {
           text,
           coding
           {
               code,
               display
           }
       },
       interpretation
        {
           text,
           coding
           {
               code,
               display
           }
       },
       method
        {
           text,
           coding
           {
               code,
               display
           }
       },  
       status,
       effective, 
        value
        {
           text,
           coding
           {
               code,
               display
           }
       },  
       subject{
           reference,
           display
       },
        performer{
           reference,
           display
       } , 
       component
       {
           value
        {
           text,
           coding
           {
               code,
               display
           }
       },  
           code
           {
               text,
               coding
               {
                   code,
                   display
               }
           }
       }
   },
   smokingStatuses
   {
       resourceId,
       code
       {
           codeableSystem,
           code,
           text,
           display
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        specimen
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       effectiveDateTime,
       issued,
       valueQuantity{
           system,
           unit,
           value,
           code
       },
       valueCodeableConcept
       {
            codeableSystem,
           code,
           text,
           display
       }
   },
   lifeStyleIndicators
   {
       resourceId,
       note,
       resourceType,
       use,
       valueCodeableConcept
       {
            codeableSystem,
           code,
           text,
           display
       }
   },
   clinicalComplainses
   {
       resourceId,
       status,
       description,
       effectiveDateTime,
       cancerPatientResourceReference
       {
            resourceId,
           resourceType,
           resourceReference,
           display
       },
       clinicalComplains
   },
   rECISTObservation
   {
      resourceId,
       code
       {
            codeableSystem,
           code,
           text,
           display
       },
       description
   },
    examinations
   {
       resourceId,
       status,
       description,
       effectiveDateTime,
       resourceName,
       cancerPatientResourceReference
       {
            resourceId,
           resourceType,
           resourceReference,
           display
       },
       code{
           codeableSystem,
           code,
           display,
           text
       }
       examinations
   },
   generalExaminations
   {
       resourceId,
       status,
       resourceName,
       description,
       effectiveDateTime,
       cancerPatientResourceReference
       {
            resourceId,
           resourceType,
           resourceReference,
           display
       },
       code{
           codeableSystem,
           code,
           display,
           text
       }
       valueCodeableConcept
       {
           codeableSystem,
           code,display,
           text
       }
   },
   systemicExaminations
   {
       resourceId,
       status,
       description,
       resourceName,
       effectiveDateTime,
       cancerPatientResourceReference
       {
            resourceId,
           resourceType,
           resourceReference,
           display
       },
       code{
           codeableSystem,
           code,
           display,
           text
       },
       valueString
   },
   inspection
   {
        resourceId,
       status,
       description,
       resourceName,
       effectiveDateTime,
       valueString
   },
   palpation
   {
        resourceId,
       status,
       description,
       resourceName,
       effectiveDateTime,
       valueString
   },
   observationLabs
   {
       resourceId,
         code
       {
            codeableSystem,
           code,
           text,
           display
       }
        valueCodeableConcept
       {
            codeableSystem,
           code,
           text,
           display
       },
       effectiveDateTime,
       status,
         valueQuantity{
           system,
           unit,
           value,
           code
       },
       cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        specimen
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       component{
          code
           {
               codeableSystem,
               code,
               text,
               display
           },
            valueQuantity{
               system,
               unit,
               value,
               code
           } 
       },
       referenceRange
       {
          text,
          high{
           system,
           unit,
           value,
           code
          },
          low{
           system,
           unit,
           value,
           code
          },
          type
           {
               codeableSystem,
               code,
               text,
               display
           },
            appliesTo
           {
               codeableSystem,
               code,
               text,
               display
           },
           age{
                       high{
                   system,
                   unit,
                   value,
                   code
               },
               low{
                   system,
                   unit,
                   value,
                   code
               }
           }
       }
   }, 
   nonCancerSpecificSpecimens
   {
       id,
        subject{
           reference,
           display
       },
       receivedTime,
       type
        {
           text,
           coding
           {
               code,
               display
           }
       },
       status,
       note{
           text{
               value
           }
       },
       collection
       {
            method
           {
               text,
               coding
               {
                   code,
                   display
               }
           },
           bodySite
           {
               text,
               coding
               {
                   code,
                   display
               }
           },
           collector{
           reference,
           display
          }
       }
   },
   nonCancerRiskAssessments
   {
       id,
       status,
       occurrence,
         subject{
           reference,
           display
       },
         performer{
           reference,
           display
       },
        basis{
           reference,
           display
       },
        reasonCode
           {
               text,
               coding
               {
                   code,
                   display
               }
           },
       method
           {
               text,
               coding
               {
                   code,
                   display
               }
           }
   },
   familyMemberHistories
   {
       resourceId,
       status,
       born,
       name,
       deceasedBoolean,
         relationship
       {
           codeableSystem,
           code,
           text,
           display
       },
        sex
       {
           codeableSystem,
           code,
           text,
           display
       },
       patient
       {
       resourceId,
       resourceType,
       resourceReference,
       display
       },
       age,
       reasonCode
       {
           codeableSystem,
           code,
           text,
           display
       }
       condition
       {
           contributedToDeath,
             code
           {
               codeableSystem,
               code,
               text,
               display
           },
            outcome
           {
               codeableSystem,
               code,
               text,
               display
           },
             onSetAge,
       }
   },
   treatmentReminders
   {
       resourceId,
       status,
       sent,
       received,
       priority,
       note,
       category{
            codeableSystem,
               code,
               text,
               display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        sender
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        recipient
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        partOf
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        basedOn
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        inResponseTo
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        about
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       payLoad
       {
           contentString,
               contentReference
           {
               resourceId,
               resourceType,
               resourceReference,
               display
           },
           contentAttachment
           {
               contentType,
               url,
               size,
               data,
               hash,
               creation
           }
       }
   },
   reminders
   {
       resourceId,
       status,
       sent,
       received,
       priority,
       note,
       category{
            codeableSystem,
               code,
               text,
               display
       },
        cancerPatientResourceReference
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        sender
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        recipient
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        partOf
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        basedOn
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        inResponseTo
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
        about
       {
           resourceId,
           resourceType,
           resourceReference,
           display
       },
       payLoad
       {
           contentString,
               contentReference
           {
               resourceId,
               resourceType,
               resourceReference,
               display
           },
           contentAttachment
           {
               contentType,
               url,
               size,
               data,
               hash,
               creation
           }
       }
   }
}
}
`;

export const GET_TIMELINE = `
query
PatientDataQuery($id:String!){
data:timeline(patientTimelineCriteria:{
  patientResourceId :$id,
 cancerResourceTypes:[
CANCER_PATIENT,
PRIMARY_CANCER_CONDITION,
SECONDARY_CANCER_CONDITION,
CoMORBID_CONDITION,
CANCER_RELATED_SURGICAL_PROCEDURE_REQUEST,
CANCER_RELATED_RADIATION_PROCEDURE,
CANCER_PATIENT_REPORTED_SYMPTOM,
ECOG_PERFORMANCE_STATUS,
KARNOFSKY_PERFORMANCE_STATUS,
TUMOR_MARKER,
VITAL_SIGNS,
CANCER_RELATED_ENCOUNTER_SURGICAL,
CANCER_RELATED_ENCOUNTER_OPD,
CANCER_ALLERGY_INTOLERANCE,
CARE_PLAN,
CANCER_RELATED_MEDICATION_STATEMENT,
CANCER_IMMUNIZATION,
CANCER_RISK_ASSESSMENT,
CANCER_DIAGNOSTIC_REPORT,
CANCER_DISEASE_STATUS,
TNM_CLINICAL_STAGE_GROUP,
TNM_CLINICAL_PRIMARY_TUMOR_CATEGORY,
TNM_PATHOLOGICAL_PRIMARY_TUMOR_CATEGORY,
TNM_PATHOLOGICAL_STAGE_GROUP,
CANCER_GENETIC_VARIANT,
GENOMIC_REGION_STUDIED,
GENETIC_SPECIMEN,
CANCER_GENOMICS_REPORT
]
})
{
    name,
    date,
    metric,
    subMetric
}
}
`;

export const GET_CRITICAL_EVENTS = `
query
PatientDataQuery($id:String!){
data:clinicalImpressionHistory(clinicalImpressionSearchCriteria:{
resourceId :$id,
nextResultUrl: null,
limit:100,
})
{
 nextResultUrl,
 recordCount
   cancerClinicalImpressions
   {
    resourceId
     status,
     date,
     description,
     protocol,
     cancerPatientResourceReference
     {
          resourceId,
            resourceType,
           resourceReference,
           display  
     },
     investigation
     {
         code
         {
             codeableSystem,
               code,
               text,
               display
         },
         item
         {
              resourceId,
            resourceType,
           resourceReference,
           display  
         }
     }
   }
}
}
`;

export const GET_PROTOCOL_LIST = `
query
PatientDataQuery($id:String!){
    data:everything(patientEverythingCriteria:{
    patientResourceId :$id,
    nextResultUrl: null,
    cancerResourceTypes:[
    CANCER_PATIENT,
    CANCER_RELATED_MEDICATION_REQUEST
    ]
    })
    {
        nextResultUrl,
        recordCount
        treatmentProtocolPlans
       {
           resourceId,
           start,
           end,
           cycle,
           regimen
      }

       
    }
    }
`;

export const GET_RELATED_CASES = `
query
PatientDataQuery($cancerType:String!, $stage: String!,$gender: String!,$resourceId: String!){
 data:similarPatient(similarPatientSearchCriteria:{
nextResultUrl:"",
sortOrder:"",
resourceId:$resourceId,
cancerStage:[$stage],
cancerType:[$cancerType],
patientType:[]
eCOG:[],
karnofsky:"null-null",
limit:0,
fromDate:null,
toDate:null,
additionalParams:[
    {
        patientSearchParamType:"Name",
        patientSearchParamValue:null
    },
     {
        patientSearchParamType:"Phone",
        patientSearchParamValue:null
    },
     {
        patientSearchParamType:"AgeLessThan",
        patientSearchParamValue:null
    },
     {
        patientSearchParamType:"AgeGreaterThan",
        patientSearchParamValue:null
    },
     {
        patientSearchParamType:"Gender",
        patientSearchParamValue:$gender
    }
 ]
})
 {  
     recordCount,
     nextResultUrl,
     cancerPatients
     {
        patient
        {
            resourceId,
            first,
            last,
            email,
            phone,
            birthDate,
            middle,
            display,
            gender,
            address,
            city,
            state,
            age
        },
        primaryCancerCondition
        {
            resourceId,
            onset,
            code
            {
                codeableSystem,
                code,
                text,
                display
            },
            bodySideWithLaterality
            {
             bodySite
            {
                codeableSystem,
                code,
                text,
                display
            },
             laterality
            {
                codeableSystem,
                code,
                text,
                display
            }
            },
            asserter
            {
               resourceId,
               resourceType,
               resourceReference,
               display
            },
            histologyMorphologyBehaviour
            {
                codeableSystem,
                code,
                text,
                display
            }
        }
     }
  
 }
}
`;

export const GET_PATIENT_OUTCOMES = `
query
PatientReportedOutcomeQuery($id:String!,$fromDate:String!,$toDate:String!){
 data:getDateWisePatientReportedSymptom(reportedSymptomDetailsInput:{
    resourceId:$id,
    fromDate:$fromDate,
    toDate:$toDate
 })
 {
     recordCount,
     nextResultUrl
     cancerPatientReportedSymptom
     {
        patientReportedSymptom
        {
            resourceId,
            status,
            date,
            subject
            {
                display,
                resourceId,
                resourceReference
            },
            reportedSymptom
            {
                code,
                response,
                colourCode,
            }
        }
   }
 }
}
`;

export const GET_REPORTS = `
query
PatientDataQuery($id:String!){
 data:documentReferenceSearch(documentReferenceCriteria:{
nextResultUrl:"",
sortOrder:"",
fromDate:null,
toDate:null,
search:"LabReport",
category:["Lab Reports","Radiology Reports",
"Discharge Summary",
"Clinical Notes",
"Prescription"],
resourceId:$id
})
 {  
     recordCount,
     nextResultUrl,
     cancerDocumentReferences
     {
        cancerDocumentReference
        {
            resourceId,
            status,
            docStatus,
            recordName,
            date,
            description,
             type
            {
                codeableSystem,
                code,
                text,
                display
            },
             category
            {
                codeableSystem,
                code,
                text,
                display
            },
            author
            {
               resourceId,
               resourceType,
               resourceReference,
               display
            },
            authenticator
            {
               resourceId,
               resourceType,
               resourceReference,
               display
            },
             cancerPatientResourceReference
            {
               resourceId,
               resourceType,
               resourceReference,
               display
            },
              custodian
            {
               resourceId,
               resourceType,
               resourceReference,
               display
            },
            relatesTo
            {
                code,
                target
               {
                resourceId,
                resourceType,
                resourceReference,
                display
                }
            },
            content
            {
                attachment
                {
                    contentType,
                    url,
                    size,
                    title,
                    hash,
                    creation
                },
                format
                {
                    codeableSystem,
                    code,
                    text,
                    display
                },
            }
        }
     }
  
 }
}
`;
